FROM ubuntu:14.04
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y apache2
COPY config/apache-config.conf /etc/apache2/sites-enabled/000-default.conf
COPY config/apache2.conf /etc/apache2/apache2.conf
RUN sed -i "s/80/8080/g" /etc/apache2/ports.conf
RUN a2enmod headers
EXPOSE 8080
